### ISSUE TITLE
auto-updater

### ISSUE THREAD

**Issue by kekkodance** [brandongallagher1999/1337x-Bot-Go#21]
is a update feature for git pulling from the repo planned? i don't wanna have to go to the github daily to check for new commits, so why not check for updates every 30 mins and update in the docker container?

**Comment by brandongallagher1999** [comment]
That's not a best practice in Docker. Docker containers aren't supposed to pull code from a git repo then build the image from there. They receive the image from a container registry, which comes from a build trigger typically on a build agent such as GitHub Actions, GitLab CI, etc.

Having a timer-based update for a container is the worst anti-pattern you can have for Docker Images as far as that goes.

**Comment by brandongallagher1999** [comment]
The process is supposed to go as such:

New code merged into master/main --> build docker image --> publish/push images to container registry --> build agent deploys that image into your infrastructure (virtual machine, Kubernetes, app service, etc).

**Comment by brandongallagher1999** [comment]
The reason why you don't have containers "auto pulling" latest code is because that completely defeats the purpose of version management. You want to have a different version tag such as "$registry/$appName:$verison" for each version of the app that has been into main so that you can easily revert to older versions of the image, should your production environment go down.

**Comment by kekkodance** [comment]
so, does the bot update itself on each docker-compose build or do i have to git pull every time?

**Comment by brandongallagher1999** [comment]
You need to git pull
